use ipnet::IpNet;
use serde::Deserialize;
use serde::Serialize;
use std::net::IpAddr;
use uuid::Uuid;

/// The type of an overlay network.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum NetworkType {
    Wireguard,
    Vxlan,
}

impl NetworkType {
    pub fn as_str(self) -> &'static str {
        match self {
            NetworkType::Wireguard => "wireguard",
            NetworkType::Vxlan => "vxlan",
        }
    }
}

/// A mutation of the cluster state, stored in the raft log.
///
/// Every variant must be deterministic: apply() resolves everything against
/// identical local state, never against random data or wall clock time.
/// Random values (e.g. enrollment tokens) are generated by the leader before
/// the entry enters the log.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Mutation {
    /// Used as the first entry of a freshly initialized log.
    Noop,
    /// Insert a new user (a natural person owning zero or more nodes).
    CreateUser { name: String, permissions: i32 },
    /// Change the permission level of a user.
    SetUserPermissions { user_id: i64, permissions: i32 },
    /// Delete a user. Nodes owned by the user keep running but lose the
    /// ownership link (user_id becomes NULL); their tokens stay valid until
    /// the node itself is deleted.
    DeleteUser { user_id: i64 },
    /// Record (or update the address of) a raft server node as a peer row,
    /// keyed by its raft public key. Idempotent: re-joining updates the
    /// advertise address.
    RecordRaftNode {
        raft_pubkey: [u8; 32],
        advertise: String,
    },
    /// Insert a new node (peer). `token` was generated by the leader and is
    /// returned to the caller once this entry is committed. The node is
    /// linked to its owning user; its effective capabilities are capped by
    /// that user's permissions at role-assignment time.
    AddPeer {
        user_id: Option<i64>,
        name: String,
        token: Uuid,
        permissions: i32,
        /// Requested addresses with their prefixes (e.g. 10.99.0.11/24). The
        /// address host part is stored verbatim; the network row is looked up
        /// by the truncated subnet.
        addresses: Vec<IpNet>,
    },
    /// Delete a peer, its addresses and the routes pointing at them.
    DeletePeer { peer_id: i64 },
    /// Change the permission level of a peer.
    SetPeerPermissions { peer_id: i64, permissions: i32 },
    /// Transfer ownership of a node to a user (admin action). The node's
    /// permission is re-capped at the new owner's level on the next role
    /// operation; ownership itself does not change node permissions.
    SetPeerOwner { peer_id: i64, user_id: i64 },
    /// Set the reported endpoint of a peer.
    SetPeerEndpoint { peer_id: i64, endpoint: String },
    /// Full self-reported state of a peer (get_addresses).
    ///
    /// The leader diffs old/new state; apply writes unconditionally and derives
    /// the matching events (new key => Deleted+New, other state => Changed).
    UpdatePeerState {
        peer_id: i64,
        pubkey: Option<[u8; 32]>,
        endpoint: Option<String>,
        nat_type: i32,
        monitor: bool,
        relay: bool,
        local_ips: Vec<IpAddr>,
        local_port: Option<u16>,
    },
    /// Add a route: destination network routed via the peer holding `via_ip`.
    AddRoute { destination: IpNet, via_ip: IpAddr },
    /// Delete a route.
    DeleteRoute { destination: IpNet, via_ip: IpAddr },
    /// Register a network (wireguard or vxlan).
    AddNetwork {
        net: IpNet,
        network_type: NetworkType,
    },
    /// Delete a network with all its addresses and routes.
    DeleteNetwork { net: IpNet },
}

/// Response of applying a mutation. Carries data the leader returns to the
/// caller, e.g. the enrollment token created by [`Mutation::AddPeer`].
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct MutationResponse {
    pub token: Option<Uuid>,
}

/// A change that was applied to the state machine, carrying the client facing
/// event payload. Emitted to the event hub after the transaction commits.
#[derive(Debug, Clone)]
pub enum AppliedChange {
    PeerNew(i64, crate::protocol::Peer),
    PeerChanged(crate::protocol::Peer),
    PeerDeleted(i64, crate::protocol::Peer),
    RouteAdded(crate::protocol::Route),
    RouteDeleted(crate::protocol::Route),
}

/// Notification about a change applied by a single log entry.
#[derive(Debug, Clone)]
pub struct AppliedEvent {
    /// Raft log index of the entry that caused this change. Used as event id.
    pub index: u64,
    pub change: AppliedChange,
}
