# .github/workflows/ci.yml
name: CI Job

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Rust ${{ matrix.rust }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
#          - os: macos-latest
#            target: x86_64-apple-darwin
#            suffix: ''
#            rust: stable
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            suffix: ''
            rust: stable
#          - os: windows-latest
#            target: x86_64-pc-windows-msvc
#            suffix: .exe
#            rust: stable
    env:
      RUST_BACKTRACE: full
      RUSTV: ${{ matrix.rust }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
      - name: Cache registry, build data
        uses: actions/cache@v2
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ./target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo
      - name: Test
        run: cargo test
      - name: Build
        run: cargo build --release
      - uses: actions/upload-artifact@master
        with:
          name: wirespider-${{ matrix.target }}
          path:  ./target/release/wirespider${{ matrix.suffix }}